import React from 'react';
import './privacy.css';

function Privacy() {
  return (
    
    <div class="card container" style={{border: 'none'}}>
        <div class="container">
        <h1 class="header_font">Privacy Policy</h1>
        <p class="content">We value the trust you place in us and recognize the importance of secure transactions and information privacy. This Privacy Policy describes how Cleartrip Private Limited (collectively referred to as “Cleartrip”, “us”, “our” or “we”), its affiliates and group companies, who provide travel related services and leisure activities (“Services”) collect, use, share or otherwise process your personal information through the websites www.cleartrip.com; www.agentbox.com; www.cleartripforbusiness.com and its sub-domains; mobile application and m-site (hereinafter, collectively referred to as “Booking Platform”).
<br/>
By visiting the Booking Platform, providing your information or availing our Services offered on the Booking Platform, you expressly agree to be bound by the terms and conditions of this Privacy Policy, the Terms of Use and any applicable Services’ terms and conditions. Your personal information will be primarily stored and processed in India and may have data protection laws that are different from those that apply in the country in which you are located. By using the Booking Platform and our Services, you consent to the transfer of information outside of your country of residence. If you do not agree to the Terms of Use or terms of this Privacy Policy, please refrain from accessing our Booking Platform or using our Services.
<br/>
We encourage you to read this Policy carefully, and to regularly check this page to review any changes we might make.</p>
        <br/>
        <h2 class="header_font_2">Collection</h2>
        <p class="content">We may collect your personal information directly from you (e.g., when you visit our Booking Platform); in course of our relationship with you (e.g., if you utilize travel services); when you make your personal information public (e.g., if you make a public post about us on social media); when you download, install or use any of our Services. We may also receive information about you from third parties (e.g., our travel partners). We may also create information about you, such as records of your interactions with us or combine data you have provided to us with data obtained from third parties such as social networks and other data collection entities. Cleartrip is not responsible for personal information you volunteer about yourself in the public domains. This Privacy Policy does not cover the practices of third parties who may provide information about you to Cleartrip. Some of the information that we may collect includes but is not limited to:</p>
        <ul>
            <li class="content">Information provided to us during sign-up/registering or using our Booking Platform such as your username or login details; e-mail id; contact number(s)</li>
            <li class="content">Booking information which includes information about your travel, Trip ID, PNR details, bookings, co-passengers, travel preferences etc.</li>
            <li class="content">Demographic information such as gender, nationality, age/date of birth</li>
            <li class="content">Location information that describes the precise geographic location of your device</li>
            <li class="content">Purchase and payment related information such as records of travel services purchases and prices; invoice records; payment records; payment method; cardholder or account-holder name; payment amount; and payment date</li>
            <li class="content">Data either created by you or by a third party and which you wish to store on our servers such as image files, documents etc.</li>
            <li class="content">Information related to any of your co-passengers or any other traveler(s) for whom you have made a booking using the Booking Platform. In such a case, you must confirm and represent that each of the other co-passengers or traveler(s) for whom a booking has been made, has agreed to have the information shared by you disclosed to us and further be shared by us with the concerned service provider(s)</li>
            <li class="content">Some sensitive personal information such as your health information or Covid 19 vaccination status or certificate in case you wish to avail any services that requires us to process the certificate/vaccination status or other such similar information strictly required in order to ensure safety from the spread of communicable diseases as required under the local regulatory requirements</li>
            <li class="content">Any other information that you may share with us or collected from you while you visit, access or use our Booking Platform or contact us for query resolution (e.g., the type of device you are using, I.P address, the internet service provider, browsing history, device identity, mobile operator, WI FI Connection, service set identifier (“SSID”), International Mobile Subscriber Identity (“IMSI”), and International Mobile Equipment Identity etc.)</li>
        </ul>
        <p class="content">If you enroll into our loyalty program or participate in third party loyalty program offered by us, we will collect and store your personal information such as name, contact number, email address, communication address, date of birth, gender, zip code, lifestyle information, demographic and work details which is provided by you to us or a third-party business partner that operates platforms where you can earn loyalty points for purchase of services or offerings, and/or also redeem them. We will also collect your information related to your transactions on Booking Platform and such third-party business partner platforms. When such a third-party business partner collects your personal information directly from you, you will be governed by their privacy policies. We shall not be responsible for the third-party business partner’s privacy practices or the content of their privacy policies, and we request you to read their privacy policies prior to disclosing any information.</p>
        <p class="content">In general, you can browse the Booking Platform without telling us who you are or revealing any personal information about yourself. Once you give us your personal information, you are not anonymous to us. Where possible, we indicate which fields are required and which fields are optional. You always have the option to not provide information, by choosing not to use a particular service or feature on the Booking Platform.</p>
        <p class="content">Our primary goal in collecting your personal information is to provide you a safe, efficient, smooth, and customized experience. This allows us to provide services and features that most likely meet your needs, and to customize our Booking Platform to make your experience safer and easier. Furthermore, the information we collect will strictly be used for legitimate, business, contractual and lawful purposes only.</p>
        <p class="content">If you receive an email, a call from a person/association claiming to be from Cleartrip seeking sensitive personal information like debit/credit card PIN, net-banking or mobile banking password, we request you to never provide such information. We at Cleartrip or our partners do not at any time connect with you requesting for such information. If you have already revealed such information, report it immediately to an appropriate law enforcement agency.</p>
        <br/>
        <h2 class="header_font_2">Use</h2>
        <p class="content">We use your personal information to provide the Services you request. Some of purposes for which we use your information are:</p>
        <ul>
            <li class="content">Provide you with the requested services, such as creating a user account, processing and confirming your reservation, and communicating with you about services requested (e.g., query resolution, regarding the feedback, etc.)</li>
            <li class="content">Analyze your travel or booking interests and provide promotional, special offers, coupons, etc.</li>
            <li class="content">Send communications related to your transactions, bookings, etc.; or send any updates to your bookings using emails, text messages, instant messaging platforms such as WhatsApp, Telegram, etc.</li>
            <li class="content">Send verification emails to ensure your identity</li>
            <li class="content">Send you marketing communications about products and services that may be relevant to you</li>
            <li class="content">Scan voice systems for quality and monitoring purposes or for improving our security levels</li>
            <li class="content">Conduct surveys or provide you with information about our Services on our Booking Platform.</li>
            <li class="content">Maintain and improve the Booking Platform, tailor the user experience, and for internal training</li>
            <li class="content">Protect your information and the Booking Platform</li>
            <li class="content">Manage our IT systems i.e., identification and mitigation of fraudulent activity; compliance with applicable law; and improving our Services</li>
            <li class="content">Exercising a right or obligation conferred or imposed by law, including responding to request and legal demands</li>
        </ul>
        <p class="content">We will ask for your permission wherever required to allow us access to SMS, contacts in your directory, camera, photo gallery, location and device information: (i) to send communication regarding your orders or other products and services; (ii) enhance your experience on the platform and provide you access to the products and services offered on the Booking Platform. You understand that your access to Services may be affected in the event permission is not provided to us. We will occasionally ask you to complete surveys conducted either by us or through a third- party market research agency. These surveys may ask you for personal information, contact information, gender, date of birth, demographic information (like pin code, age or income level) attributes such as your interests, household or lifestyle information, and other such information that you may choose to provide. The survey may involve collection of voice data or video recordings. Participation in these surveys is purely voluntary in nature. We use this data to tailor your experience at our Booking Platform, providing you with content that we think you might be interested in and to display content according to your preferences. By sharing this information with us or by participating in such surveys, you consent us in processing your personal information.</p>
        <br/>
        <h2 class="header_font_2">Cookies</h2>
        <p class="content">We use data collection devices such as "cookies" on certain pages of the Booking Platform to help analyze our web page flow, measure promotional effectiveness, and promote trust and safety. "Cookies" are small files placed on your hard drive that assist us in providing our services. We store page views, clicks and search terms used for ad personalization targeting separately from your personal information. We can’t identify you personally through the use of these cookies, but third parties who provide these cookies may be able to. We offer certain features that are only available through the use of a "cookie". We also use cookies to allow you to enter your password less frequently during a session. Cookies can also help us provide information that is targeted to your interests. Most cookies are "session cookies," meaning that they are automatically deleted from your hard drive at the end of a session. You are always free to decline/delete our cookies if your browser permits, although in that case you may not be able to use certain features on the Booking Platform and you may be required to re-enter your password more frequently during a session. Additionally, you may encounter "cookies" or other similar devices on certain pages of the Booking Platform that are placed by third parties. We do not control the use of cookies by third parties. We use cookies from third-party partners such as Google Analytics for marketing and analytical purposes. Google Analytics helps us understand how our customers use the site. You can read more about how Google uses your personal information here: https://www.google.com/intl/en/policies/privacy/. You can also opt-out of Google Analytics here: https://tools.google.com/dlpage/gaoptout. You can control the use of cookies at the individual browser level, but if you choose to disable cookies, it may limit your use of certain features or functions on the Services. Please see our Cookie Policy for more information, including a more in-depth explanation of what cookies are, the different types of cookies used on the Services, and how to change or delete them.</p>
        <br/>
        <h2 class="header_font_2">Lawful basis for processing your personal information</h2>
        <p class="content">We may process your personal information where:</p>
        <ul>
            <li class="content">You have given your consent (this legal basis is only used in relation to processing that is entirely voluntary, it is not used for processing that is necessary for meeting our obligations, required under applicable law or for legitimate interests)</li>
            <li class="content">Processing is necessary for a contract between you and us or for legitimate interests</li>
            <li class="content">Processing is required by applicable law</li>
            <li class="content">Processing is necessary for prompt action, such as in events of medical emergencies, disasters, and breakdowns of law and order</li>
            <li class="content">Processing is necessary for reasonable purposes, such as whistleblowing, mergers and acquisitions etc.</li>
            <li class="content">Processing is necessary for legal purposes or where we have a valid and legitimate interest in processing.</li>
        </ul>
        </div>
    </div>
  )
}

export default Privacy